/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_TFLITE_LEARN_161053_5_H_
#define _EI_CLASSIFIER_TFLITE_LEARN_161053_5_H_

// NOTE: As of February 2025 we've changed the default way to include binary model files.
// Instead of embedding the file as as a byte array in this file, we now use INCBIN instead;
// as it yields much shorter link times, and lower memory usage when building applications.
// If this causes issues to your builds (maybe the reason why you're visiting this file)
// you can go to **Dashboard > Experiments > Use xxd instead of INCBIN to link TFLite/ONNX files**
// to re-enable the previous behavior. Please also let us know at the forum (https://forum.edgeimpulse.com/)
// or through your Solutions Engineers (if applicable) what target you're building for, and what
// issues arise.

#define INCBIN_STYLE INCBIN_STYLE_SNAKE

#if defined(EI_MODEL_SECTION)
#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)
#define INCBIN_OUTPUT_SECTION STRINGIZE_VALUE_OF(EI_MODEL_SECTION)
#endif

#include "edge-impulse-sdk/third_party/incbin/incbin.h"

#define EI_CLASSIFIER_TFLITE_LEARN_161053_5_ARENA_SIZE     4427430
const size_t tflite_learn_161053_5_arena_size = 4427430;

INCBIN(incbin_tflite_learn_161053_5, "tflite-model/tflite_learn_161053_5.tflite");

const unsigned char *tflite_learn_161053_5 = gincbin_tflite_learn_161053_5_data;
unsigned int tflite_learn_161053_5_len = gincbin_tflite_learn_161053_5_size;

#endif // _EI_CLASSIFIER_TFLITE_LEARN_161053_5_H_

